/**
 * views/briefing.js
 *
 * The Briefing tab — the paste-ready output of the "Met Irma" pipeline.
 *
 * Each day (next 7) shows two generated Dutch texts:
 *   1. a Caren cluster line (pasted into Caren → Nedap Luna display), and
 *   2. a WhatsApp evening-reminder draft (forwarded in the family group).
 *
 * Texts are generated by the private irma-sync job and are read-only here.
 * Members can only copy them and flip the "sent" status. The actual paste and
 * send are always performed by a human — this view ends at ready-to-paste text.
 */

import { fetchBriefings, markBriefingSent, reopenBriefing } from '../api.js';
import { getState }   from '../state.js';
import { escapeHtml, formatRelative } from '../utils.js';

const STATUS_BADGE = {
  ready:              { label: 'Klaar',                     cls: 'briefing-badge--ready'   },
  sent:               { label: 'Verzonden ✓',          cls: 'briefing-badge--sent'    },
  changed_after_sent: { label: 'Gewijzigd na verzending!',  cls: 'briefing-badge--changed' },
};

/**
 * @param {HTMLElement} container
 * @param {{ familyId: string|null }} state
 */
export async function mount(container, { familyId }) {
  container.innerHTML = `
    <div class="view-briefing">
      <div class="view-header">
        <h1>Briefing</h1>
      </div>
      <div id="briefing-content">
        <div class="section-loading">Briefings laden…</div>
      </div>
    </div>
  `;

  const contentEl = container.querySelector('#briefing-content');

  if (!familyId) {
    contentEl.innerHTML = '<p class="empty-state">Familie niet gevonden.</p>';
    return;
  }

  /** @type {Array} */
  let briefings = [];

  async function load() {
    try {
      briefings = await fetchBriefings(familyId, { limit: 7 });
      render();
    } catch (err) {
      console.error('[ma/briefing] Failed to load briefings:', err);
      contentEl.innerHTML =
        '<p class="empty-state">Kon de briefings niet laden. Probeer het opnieuw.</p>';
    }
  }

  function render() {
    if (!briefings.length) {
      contentEl.innerHTML =
        '<p class="empty-state">Nog geen briefings. De synchronisatie draait elk uur.</p>';
      return;
    }
    contentEl.innerHTML = briefings.map(renderCard).join('');
    wire();
  }

  function wire() {
    // Copy buttons — write to clipboard inside the user gesture (iOS Safari).
    contentEl.querySelectorAll('[data-copy]').forEach(btn => {
      btn.addEventListener('click', () => {
        const briefing = briefings.find(b => b.id === btn.dataset.id);
        if (!briefing) return;
        const text = btn.dataset.copy === 'caren'
          ? briefing.caren_text
          : briefing.whatsapp_text;
        copyToClipboard(btn, text);
      });
    });

    // Sent / reopen toggle.
    contentEl.querySelectorAll('[data-toggle]').forEach(btn => {
      btn.addEventListener('click', () => toggleSent(btn));
    });
  }

  async function toggleSent(btn) {
    const briefing = briefings.find(b => b.id === btn.dataset.id);
    if (!briefing) return;

    const wasSent = briefing.status === 'sent';
    const userId  = getState().user?.id ?? null;

    btn.disabled = true;
    try {
      const updated = wasSent
        ? await reopenBriefing(briefing.id)
        : await markBriefingSent(briefing.id, userId);
      Object.assign(briefing, updated);
      render();
    } catch (err) {
      console.error('[ma/briefing] Failed to update status:', err);
      btn.disabled = false;
      btn.textContent = 'Kon status niet wijzigen';
    }
  }

  await load();
}

/**
 * Copies `text`, flashing the button label to confirm. iOS Safari requires
 * the writeText call to happen inside the click handler's user gesture.
 */
function copyToClipboard(btn, text) {
  const restore = btn.textContent;
  navigator.clipboard.writeText(text ?? '').then(() => {
    btn.textContent = 'Gekopieerd ✓';
    btn.classList.add('briefing-copy--done');
    setTimeout(() => {
      btn.textContent = restore;
      btn.classList.remove('briefing-copy--done');
    }, 1500);
  }).catch(err => {
    console.error('[ma/briefing] Clipboard write failed:', err);
    btn.textContent = 'Kopiëren mislukt';
    setTimeout(() => { btn.textContent = restore; }, 1500);
  });
}

/**
 * Renders one day's briefing card as an HTML string. Everything user-facing is
 * escaped; generated texts are shown with their line breaks preserved via CSS.
 */
function renderCard(b) {
  const badge = STATUS_BADGE[b.status] ?? STATUS_BADGE.ready;
  const toggleLabel = b.status === 'sent' ? 'Heropen' : 'Markeer als verzonden';

  const carenBlock = b.caren_text
    ? `
      <div class="briefing-block">
        <div class="briefing-block-head">
          <span class="briefing-block-label">Caren</span>
          <button class="briefing-copy" data-copy="caren" data-id="${escapeHtml(b.id)}">
            Kopieer Caren-regel
          </button>
        </div>
        <pre class="briefing-text briefing-text--mono">${escapeHtml(b.caren_text)}</pre>
      </div>`
    : '';

  const whatsappBlock = b.whatsapp_text
    ? `
      <div class="briefing-block">
        <div class="briefing-block-head">
          <span class="briefing-block-label">WhatsApp</span>
          <button class="briefing-copy" data-copy="whatsapp" data-id="${escapeHtml(b.id)}">
            Kopieer WhatsApp-bericht
          </button>
        </div>
        <pre class="briefing-text">${escapeHtml(b.whatsapp_text)}</pre>
      </div>`
    : '';

  return `
    <article class="briefing-card">
      <header class="briefing-card-head">
        <h2 class="briefing-date">${escapeHtml(formatDutchDate(b.briefing_date))}</h2>
        <span class="briefing-badge ${badge.cls}">${escapeHtml(badge.label)}</span>
      </header>
      ${carenBlock}
      ${whatsappBlock}
      <div class="briefing-actions">
        <button class="briefing-toggle" data-toggle data-id="${escapeHtml(b.id)}">
          ${escapeHtml(toggleLabel)}
        </button>
      </div>
      <footer class="briefing-foot">
        Laatst bijgewerkt: ${escapeHtml(formatRelative(b.generated_at))}
      </footer>
    </article>
  `;
}

/**
 * Formats a YYYY-MM-DD date as a Dutch weekday + date, e.g. "vrijdag 17 juli".
 * Parsed as a local calendar date to avoid a timezone day-shift.
 */
function formatDutchDate(dateStr) {
  const [y, m, d] = String(dateStr).split('-').map(Number);
  const date = new Date(y, (m || 1) - 1, d || 1);
  return date.toLocaleDateString('nl-NL', {
    weekday: 'long',
    day:     'numeric',
    month:   'long',
  });
}
